package brain

import (
	"context"
	"io"
	"strings"
	"time"

	"github.com/SynapsesOS/synapses-intelligence/config"
	"github.com/SynapsesOS/synapses-intelligence/internal/contextbuilder"
	"github.com/SynapsesOS/synapses-intelligence/internal/enricher"
	"github.com/SynapsesOS/synapses-intelligence/internal/guardian"
	"github.com/SynapsesOS/synapses-intelligence/internal/ingestor"
	"github.com/SynapsesOS/synapses-intelligence/internal/llm"
	"github.com/SynapsesOS/synapses-intelligence/internal/orchestrator"
	"github.com/SynapsesOS/synapses-intelligence/internal/pruner"
	"github.com/SynapsesOS/synapses-intelligence/internal/sdlc"
	"github.com/SynapsesOS/synapses-intelligence/internal/store"
)

// supportsThinking returns true for models that support Qwen3.x thinking mode
// (/think and /no_think prompt prefixes). Qwen2.5 and other non-Qwen3 models
// do not understand these prefixes and produce garbage output when they are sent.
func supportsThinking(model string) bool {
	lower := strings.ToLower(model)
	// Match "qwen3" prefix: covers qwen3:1b, qwen3.5:4b, qwen3:8b, etc.
	return strings.HasPrefix(lower, "qwen3")
}

// Brain is the public interface for the Thinking Brain.
// All methods are safe for concurrent use.
// Use New() to create a configured instance.
// Use NullBrain when the brain is disabled — all methods return zero values.
type Brain interface {
	// Ingest summarizes a changed code snippet and persists it in brain.sqlite.
	// Called on file-save events for changed functions/methods/structs.
	// Returns immediately if LLM is unavailable.
	Ingest(ctx context.Context, req IngestRequest) (IngestResponse, error)

	// Enrich adds semantic summaries and a 2-sentence insight to a carved context subgraph.
	// Summaries are loaded from brain.sqlite (fast path, no LLM call).
	// Insight is generated by the LLM only if Enrich feature is enabled.
	Enrich(ctx context.Context, req EnrichRequest) (EnrichResponse, error)

	// ExplainViolation generates a plain-English explanation and fix for a rule violation.
	// Results are cached in brain.sqlite to avoid repeated LLM calls for the same violation.
	ExplainViolation(ctx context.Context, req ViolationRequest) (ViolationResponse, error)

	// Coordinate suggests work distribution when agents conflict on a scope.
	Coordinate(ctx context.Context, req CoordinateRequest) (CoordinateResponse, error)

	// Summary returns the stored semantic summary for a node ID.
	// Returns "" if no summary has been ingested for this node.
	Summary(nodeID string) string

	// Available returns true if the configured LLM backend is reachable.
	Available() bool

	// ModelName returns the configured LLM model tag.
	ModelName() string

	// EnsureModel checks if the configured model is present locally; if not,
	// it pulls it from the Ollama registry, streaming progress to w.
	// Returns nil when the model is ready, an error if the pull fails.
	EnsureModel(ctx context.Context, w io.Writer) error

	// --- v0.2.0: Context Packet, SDLC, Learning ---

	// BuildContextPacket assembles a structured Context Packet for an agent.
	// Returns nil (with no error) when the Brain is unavailable — callers fall
	// back to raw Synapses context unchanged.
	BuildContextPacket(ctx context.Context, req ContextPacketRequest) (*ContextPacket, error)

	// LogDecision records an agent's completed work and updates co-occurrence
	// patterns in brain.sqlite. Non-fatal; errors are returned but do not
	// block the calling agent.
	LogDecision(ctx context.Context, req DecisionRequest) error

	// SetSDLCPhase persists the project's current SDLC phase.
	SetSDLCPhase(phase SDLCPhase, agentID string) error

	// SetQualityMode persists the project's current quality mode.
	SetQualityMode(mode QualityMode, agentID string) error

	// GetSDLCConfig returns the current SDLC config.
	GetSDLCConfig() SDLCConfig

	// GetPatterns returns learned co-occurrence patterns sorted by confidence.
	// If trigger is non-empty, only patterns with that trigger are returned.
	// limit caps the number of results (0 = default of 20).
	GetPatterns(trigger string, limit int) []PatternHint

	// Prune strips boilerplate (navigation, ads, footers) from raw web page text
	// using the Tier 0 (0.8B) model. Returns cleaned technical content.
	// Falls back to returning the original content if the LLM is unavailable.
	Prune(ctx context.Context, content string) (string, error)

	// --- v0.6.0: ADRs ---

	// UpsertADR creates or updates an Architectural Decision Record.
	UpsertADR(req ADRRequest) error

	// GetADR returns the ADR with the given ID.
	GetADR(id string) (ADR, error)

	// AllADRs returns all ADRs ordered by updated_at descending.
	AllADRs() ([]ADR, error)

	// GetADRsForFile returns accepted ADRs whose linked_files patterns match the given file path.
	GetADRsForFile(filePath string, limit int) ([]ADR, error)
}

// impl is the production Brain backed by Ollama + SQLite.
type impl struct {
	cfg          config.BrainConfig
	llm          llm.LLMClient
	store        *store.Store
	ingestor     *ingestor.Ingestor
	enricher     *enricher.Enricher
	guardian     *guardian.Guardian
	orchestrator *orchestrator.Orchestrator
	pruner       *pruner.Pruner
	sdlcMgr      *sdlc.Manager
	builder      *contextbuilder.Builder
	learner      *contextbuilder.Learner
}

// New creates a fully-configured Brain from cfg.
// Returns NullBrain if cfg.Enabled is false.
// Returns NullBrain (with logged warning) if the store cannot be opened.
func New(cfg config.BrainConfig) Brain {
	if !cfg.Enabled {
		return &NullBrain{}
	}

	// Build LLM clients.
	// When backend="local" and gguf_path is set, all four tiers share one LocalClient
	// that runs the fine-tuned SIL GGUF model directly in-process (no Ollama required).
	// Falls back to OllamaClient if the local model can't be loaded.
	var (
		ingestClient      llm.LLMClient
		guardianClient    llm.LLMClient
		enrichClient      llm.LLMClient
		orchestrateClient llm.LLMClient
	)

	if cfg.Backend == "local" && cfg.GGUFPath != "" {
		hw := llm.DetectHardware()
		localCli, err := llm.NewLocalClient(cfg.GGUFPath, hw)
		if err == nil {
			// Single fine-tuned model serves all four tiers.
			// Thinking enabled — SIL model was trained with <think> blocks.
			localCli.WithThinking(true)
			ingestClient = localCli
			guardianClient = localCli
			enrichClient = localCli
			orchestrateClient = localCli
		}
		// err is non-fatal — fall through to Ollama below.
	}

	// Ollama path: used when backend!="local" or local client failed to load.
	if ingestClient == nil {
		// Tiered Nervous System: each task uses the model best suited to its complexity.
		// Tier 0 (Reflex) — ingest: fast summarization, no reasoning. Default: qwen3.5:0.8b.
		ingestClient = llm.NewOllamaClient(cfg.OllamaURL, cfg.ModelIngest, cfg.TimeoutMS).WithThinking(false)
		// Tier 1 (Sensory) — guardian: plain-English violation explanations. Default: qwen3.5:2b.
		guardianClient = llm.NewOllamaClient(cfg.OllamaURL, cfg.ModelGuardian, cfg.TimeoutMS).WithThinking(false)
		// Tier 2 (Specialist) — enricher: architectural insight + concerns. Default: qwen3.5:4b.
		enrichClient = llm.NewOllamaClient(cfg.OllamaURL, cfg.ModelEnrich, cfg.TimeoutMS).WithThinking(supportsThinking(cfg.ModelEnrich))
		// Tier 3 (Architect) — orchestrator: multi-agent conflict resolution. Default: qwen3.5:9b.
		orchestrateClient = llm.NewOllamaClient(cfg.OllamaURL, cfg.ModelOrchestrate, cfg.TimeoutMS).WithThinking(supportsThinking(cfg.ModelOrchestrate))
	}

	st, err := store.Open(cfg.DBPath)
	if err != nil {
		// Can't open store — degrade gracefully.
		return &NullBrain{}
	}

	timeout := time.Duration(cfg.TimeoutMS) * time.Millisecond

	enr := enricher.New(enrichClient, st, timeout)
	mgr := sdlc.NewManager(st)

	b := &impl{
		cfg:          cfg,
		llm:          enrichClient, // primary client used for Available() / ModelName()
		store:        st,
		ingestor:     ingestor.New(ingestClient, st, timeout),
		enricher:     enr,
		guardian:     guardian.New(guardianClient, st, timeout),
		orchestrator: orchestrator.New(orchestrateClient, timeout),
		pruner:       pruner.New(ingestClient, timeout), // Tier 0: 0.8B, same as ingest
		sdlcMgr:      mgr,
		builder:      contextbuilder.New(st, mgr, enr),
		learner:      contextbuilder.NewLearner(st),
	}
	return b
}

func (b *impl) Ingest(ctx context.Context, req IngestRequest) (IngestResponse, error) {
	if !b.cfg.Ingest {
		return IngestResponse{NodeID: req.NodeID}, nil
	}
	r, err := b.ingestor.Summarize(ctx, ingestor.Request{
		NodeID:   req.NodeID,
		NodeName: req.NodeName,
		NodeType: req.NodeType,
		Package:  req.Package,
		Code:     req.Code,
	})
	if err != nil {
		return IngestResponse{NodeID: req.NodeID}, err
	}
	return IngestResponse{NodeID: r.NodeID, Summary: r.Summary, Tags: r.Tags}, nil
}

func (b *impl) Enrich(ctx context.Context, req EnrichRequest) (EnrichResponse, error) {
	// Always load summaries from SQLite — fast path, no LLM.
	summaries := b.store.GetSummaries(req.AllNodeIDs)

	if !b.cfg.Enrich {
		return EnrichResponse{Summaries: summaries}, nil
	}

	r, err := b.enricher.Enrich(ctx, enricher.Request{
		RootID:       req.RootID,
		RootName:     req.RootName,
		RootType:     req.RootType,
		CalleeNames:  req.CalleeNames,
		CallerNames:  req.CallerNames,
		RelatedNames: req.RelatedNames,
		TaskContext:  req.TaskContext,
	})
	if err != nil {
		// Return summaries even if insight generation failed.
		return EnrichResponse{Summaries: summaries}, nil
	}
	return EnrichResponse{
		Insight:   r.Insight,
		Concerns:  r.Concerns,
		Summaries: summaries,
		LLMUsed:   r.LLMUsed,
	}, nil
}

func (b *impl) ExplainViolation(ctx context.Context, req ViolationRequest) (ViolationResponse, error) {
	if !b.cfg.Guardian {
		return ViolationResponse{}, nil
	}
	r, err := b.guardian.Explain(ctx, guardian.Request{
		RuleID:       req.RuleID,
		RuleSeverity: req.RuleSeverity,
		Description:  req.Description,
		SourceFile:   req.SourceFile,
		TargetName:   req.TargetName,
	})
	if err != nil {
		return ViolationResponse{}, err
	}
	return ViolationResponse{Explanation: r.Explanation, Fix: r.Fix}, nil
}

func (b *impl) Coordinate(ctx context.Context, req CoordinateRequest) (CoordinateResponse, error) {
	if !b.cfg.Orchestrate {
		return CoordinateResponse{}, nil
	}

	claims := make([]orchestrator.WorkClaim, len(req.ConflictingClaims))
	for i, c := range req.ConflictingClaims {
		claims[i] = orchestrator.WorkClaim{
			AgentID:   c.AgentID,
			Scope:     c.Scope,
			ScopeType: c.ScopeType,
		}
	}
	r, err := b.orchestrator.Coordinate(ctx, orchestrator.Request{
		NewAgentID:        req.NewAgentID,
		NewScope:          req.NewScope,
		ConflictingClaims: claims,
	})
	if err != nil {
		return CoordinateResponse{}, err
	}
	return CoordinateResponse{
		Suggestion:       r.Suggestion,
		AlternativeScope: r.AlternativeScope,
	}, nil
}

func (b *impl) Prune(ctx context.Context, content string) (string, error) {
	return b.pruner.Prune(ctx, content)
}

func (b *impl) Summary(nodeID string) string {
	if b.store == nil {
		return ""
	}
	return b.store.GetSummary(nodeID)
}

func (b *impl) Available() bool {
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	return b.llm.Available(ctx)
}

func (b *impl) ModelName() string {
	return b.llm.ModelName()
}

func (b *impl) EnsureModel(ctx context.Context, w io.Writer) error {
	if b.llm.ModelPulled(ctx) {
		return nil
	}
	return b.llm.PullModel(ctx, w)
}

func (b *impl) BuildContextPacket(ctx context.Context, req ContextPacketRequest) (*ContextPacket, error) {
	if !b.cfg.ContextBuilder {
		return nil, nil // feature disabled; caller uses raw context
	}
	pkt, err := b.builder.Build(ctx, contextbuilder.Request{
		AgentID:         req.AgentID,
		Phase:           string(req.Phase),
		QualityMode:     string(req.QualityMode),
		EnableLLM:       req.EnableLLM,
		RootNodeID:      req.Snapshot.RootNodeID,
		RootName:        req.Snapshot.RootName,
		RootType:        req.Snapshot.RootType,
		RootFile:        req.Snapshot.RootFile,
		CalleeNames:     req.Snapshot.CalleeNames,
		CallerNames:     req.Snapshot.CallerNames,
		RelatedNames:    req.Snapshot.RelatedNames,
		ApplicableRules: toBuilderRules(req.Snapshot.ApplicableRules),
		ActiveClaims:    toBuilderClaims(req.Snapshot.ActiveClaims),
		TaskContext:     req.Snapshot.TaskContext,
		TaskID:          req.Snapshot.TaskID,
		HasTests:        req.Snapshot.HasTests,
		FanIn:           req.Snapshot.FanIn,
		RootDoc:         req.Snapshot.RootDoc,
	})
	if err != nil || pkt == nil {
		return nil, err
	}
	return toContextPacket(pkt), nil
}

func (b *impl) LogDecision(_ context.Context, req DecisionRequest) error {
	return b.learner.RecordDecision(contextbuilder.DecisionInput{
		AgentID:         req.AgentID,
		Phase:           req.Phase,
		EntityName:      req.EntityName,
		Action:          req.Action,
		RelatedEntities: req.RelatedEntities,
		Outcome:         req.Outcome,
		Notes:           req.Notes,
	})
}

func (b *impl) SetSDLCPhase(phase SDLCPhase, agentID string) error {
	return b.sdlcMgr.SetPhase(string(phase), agentID)
}

func (b *impl) SetQualityMode(mode QualityMode, agentID string) error {
	return b.sdlcMgr.SetQualityMode(string(mode), agentID)
}

func (b *impl) GetSDLCConfig() SDLCConfig {
	row := b.sdlcMgr.GetConfig()
	return SDLCConfig{
		Phase:       SDLCPhase(row.Phase),
		QualityMode: QualityMode(row.QualityMode),
		UpdatedAt:   row.UpdatedAt,
		UpdatedBy:   row.UpdatedBy,
	}
}

func (b *impl) GetPatterns(trigger string, limit int) []PatternHint {
	if limit <= 0 {
		limit = 20
	}
	var raw []store.ContextPattern
	if trigger != "" {
		raw = b.store.GetPatternsForTriggers([]string{trigger}, limit)
	} else {
		all, _ := b.store.AllPatterns()
		if len(all) > limit {
			all = all[:limit]
		}
		raw = all
	}
	out := make([]PatternHint, len(raw))
	for i, p := range raw {
		out[i] = PatternHint{Trigger: p.Trigger, CoChange: p.CoChange, Reason: p.Reason, Confidence: p.Confidence}
	}
	return out
}

// --- conversion helpers ---

func toBuilderRules(rules []RuleInput) []contextbuilder.RuleRef {
	out := make([]contextbuilder.RuleRef, len(rules))
	for i, r := range rules {
		out[i] = contextbuilder.RuleRef{RuleID: r.RuleID, Severity: r.Severity, Description: r.Description}
	}
	return out
}

func toBuilderClaims(claims []ClaimInput) []contextbuilder.ClaimRef {
	out := make([]contextbuilder.ClaimRef, len(claims))
	for i, c := range claims {
		out[i] = contextbuilder.ClaimRef{AgentID: c.AgentID, Scope: c.Scope, ScopeType: c.ScopeType, ExpiresAt: c.ExpiresAt}
	}
	return out
}

func toContextPacket(p *contextbuilder.Packet) *ContextPacket {
	pkt := &ContextPacket{
		AgentID:             p.AgentID,
		EntityName:          p.EntityName,
		EntityType:          p.EntityType,
		GeneratedAt:         p.GeneratedAt,
		Phase:               SDLCPhase(p.Phase),
		QualityMode:         QualityMode(p.QualityMode),
		RootSummary:         p.RootSummary,
		DependencySummaries: p.DependencySummaries,
		Insight:             p.Insight,
		Concerns:            p.Concerns,
		PhaseGuidance:       p.PhaseGuidance,
		LLMUsed:             p.LLMUsed,
		PacketQuality:       p.PacketQuality,
		GraphWarnings:       p.GraphWarnings,
		QualityGate: QualityGate{
			RequireTests:   p.Gate.RequireTests,
			RequireDocs:    p.Gate.RequireDocs,
			RequirePRCheck: p.Gate.RequirePRCheck,
			Checklist:      p.Gate.Checklist,
		},
	}
	for _, c := range p.ActiveConstraints {
		pkt.ActiveConstraints = append(pkt.ActiveConstraints, ConstraintItem{
			RuleID: c.RuleID, Severity: c.Severity, Description: c.Description, Hint: c.Hint,
		})
	}
	for _, a := range p.TeamStatus {
		pkt.TeamStatus = append(pkt.TeamStatus, AgentStatus{
			AgentID: a.AgentID, Scope: a.Scope, ScopeType: a.ScopeType, ExpiresIn: a.ExpiresIn,
		})
	}
	for _, ph := range p.PatternHints {
		pkt.PatternHints = append(pkt.PatternHints, PatternHint{
			Trigger: ph.Trigger, CoChange: ph.CoChange, Reason: ph.Reason, Confidence: ph.Confidence,
		})
	}
	return pkt
}

// --- ADR methods ---

func (b *impl) UpsertADR(req ADRRequest) error {
	return b.store.UpsertADR(store.ADR{
		ID:           req.ID,
		Title:        req.Title,
		Status:       req.Status,
		ContextText:  req.ContextText,
		Decision:     req.Decision,
		Consequences: req.Consequences,
		LinkedFiles:  req.LinkedFiles,
	})
}

func (b *impl) GetADR(id string) (ADR, error) {
	a, err := b.store.GetADR(id)
	if err != nil {
		return ADR{}, err
	}
	return storeADRtoBrain(a), nil
}

func (b *impl) AllADRs() ([]ADR, error) {
	adrs, err := b.store.AllADRs()
	if err != nil {
		return nil, err
	}
	out := make([]ADR, len(adrs))
	for i, a := range adrs {
		out[i] = storeADRtoBrain(a)
	}
	return out, nil
}

func (b *impl) GetADRsForFile(filePath string, limit int) ([]ADR, error) {
	adrs, err := b.store.GetADRsForFile(filePath, limit)
	if err != nil {
		return nil, err
	}
	out := make([]ADR, len(adrs))
	for i, a := range adrs {
		out[i] = storeADRtoBrain(a)
	}
	return out, nil
}

func storeADRtoBrain(a store.ADR) ADR {
	return ADR{
		ID:           a.ID,
		Title:        a.Title,
		Status:       a.Status,
		ContextText:  a.ContextText,
		Decision:     a.Decision,
		Consequences: a.Consequences,
		LinkedFiles:  a.LinkedFiles,
		CreatedAt:    a.CreatedAt,
		UpdatedAt:    a.UpdatedAt,
	}
}
