package brain

import (
	"context"
	"io"
	"time"

	"github.com/Divish1032/synapses-intelligence/config"
	"github.com/Divish1032/synapses-intelligence/internal/contextbuilder"
	"github.com/Divish1032/synapses-intelligence/internal/enricher"
	"github.com/Divish1032/synapses-intelligence/internal/guardian"
	"github.com/Divish1032/synapses-intelligence/internal/ingestor"
	"github.com/Divish1032/synapses-intelligence/internal/llm"
	"github.com/Divish1032/synapses-intelligence/internal/orchestrator"
	"github.com/Divish1032/synapses-intelligence/internal/sdlc"
	"github.com/Divish1032/synapses-intelligence/internal/store"
)

// Brain is the public interface for the Thinking Brain.
// All methods are safe for concurrent use.
// Use New() to create a configured instance.
// Use NullBrain when the brain is disabled — all methods return zero values.
type Brain interface {
	// Ingest summarizes a changed code snippet and persists it in brain.sqlite.
	// Called on file-save events for changed functions/methods/structs.
	// Returns immediately if LLM is unavailable.
	Ingest(ctx context.Context, req IngestRequest) (IngestResponse, error)

	// Enrich adds semantic summaries and a 2-sentence insight to a carved context subgraph.
	// Summaries are loaded from brain.sqlite (fast path, no LLM call).
	// Insight is generated by the LLM only if Enrich feature is enabled.
	Enrich(ctx context.Context, req EnrichRequest) (EnrichResponse, error)

	// ExplainViolation generates a plain-English explanation and fix for a rule violation.
	// Results are cached in brain.sqlite to avoid repeated LLM calls for the same violation.
	ExplainViolation(ctx context.Context, req ViolationRequest) (ViolationResponse, error)

	// Coordinate suggests work distribution when agents conflict on a scope.
	Coordinate(ctx context.Context, req CoordinateRequest) (CoordinateResponse, error)

	// Summary returns the stored semantic summary for a node ID.
	// Returns "" if no summary has been ingested for this node.
	Summary(nodeID string) string

	// Available returns true if the configured LLM backend is reachable.
	Available() bool

	// ModelName returns the configured LLM model tag.
	ModelName() string

	// EnsureModel checks if the configured model is present locally; if not,
	// it pulls it from the Ollama registry, streaming progress to w.
	// Returns nil when the model is ready, an error if the pull fails.
	EnsureModel(ctx context.Context, w io.Writer) error

	// --- v0.2.0: Context Packet, SDLC, Learning ---

	// BuildContextPacket assembles a structured Context Packet for an agent.
	// Returns nil (with no error) when the Brain is unavailable — callers fall
	// back to raw Synapses context unchanged.
	BuildContextPacket(ctx context.Context, req ContextPacketRequest) (*ContextPacket, error)

	// LogDecision records an agent's completed work and updates co-occurrence
	// patterns in brain.sqlite. Non-fatal; errors are returned but do not
	// block the calling agent.
	LogDecision(ctx context.Context, req DecisionRequest) error

	// SetSDLCPhase persists the project's current SDLC phase.
	SetSDLCPhase(phase SDLCPhase, agentID string) error

	// SetQualityMode persists the project's current quality mode.
	SetQualityMode(mode QualityMode, agentID string) error

	// GetSDLCConfig returns the current SDLC config.
	GetSDLCConfig() SDLCConfig

	// GetPatterns returns learned co-occurrence patterns sorted by confidence.
	// If trigger is non-empty, only patterns with that trigger are returned.
	// limit caps the number of results (0 = default of 20).
	GetPatterns(trigger string, limit int) []PatternHint
}

// impl is the production Brain backed by Ollama + SQLite.
type impl struct {
	cfg          config.BrainConfig
	llm          llm.LLMClient
	store        *store.Store
	ingestor     *ingestor.Ingestor
	enricher     *enricher.Enricher
	guardian     *guardian.Guardian
	orchestrator *orchestrator.Orchestrator
	sdlcMgr      *sdlc.Manager
	builder      *contextbuilder.Builder
	learner      *contextbuilder.Learner
}

// New creates a fully-configured Brain from cfg.
// Returns NullBrain if cfg.Enabled is false.
// Returns NullBrain (with logged warning) if the store cannot be opened.
func New(cfg config.BrainConfig) Brain {
	if !cfg.Enabled {
		return &NullBrain{}
	}

	ollamaClient := llm.NewOllamaClient(cfg.OllamaURL, cfg.Model, cfg.TimeoutMS)

	st, err := store.Open(cfg.DBPath)
	if err != nil {
		// Can't open store — degrade gracefully.
		return &NullBrain{}
	}

	timeout := time.Duration(cfg.TimeoutMS) * time.Millisecond

	enr := enricher.New(ollamaClient, st, timeout)
	mgr := sdlc.NewManager(st)

	b := &impl{
		cfg:          cfg,
		llm:          ollamaClient,
		store:        st,
		ingestor:     ingestor.New(ollamaClient, st, timeout),
		enricher:     enr,
		guardian:     guardian.New(ollamaClient, st, timeout),
		orchestrator: orchestrator.New(ollamaClient, timeout),
		sdlcMgr:      mgr,
		builder:      contextbuilder.New(st, mgr, enr),
		learner:      contextbuilder.NewLearner(st),
	}
	return b
}

func (b *impl) Ingest(ctx context.Context, req IngestRequest) (IngestResponse, error) {
	if !b.cfg.Ingest {
		return IngestResponse{NodeID: req.NodeID}, nil
	}
	r, err := b.ingestor.Summarize(ctx, ingestor.Request{
		NodeID:   req.NodeID,
		NodeName: req.NodeName,
		NodeType: req.NodeType,
		Package:  req.Package,
		Code:     req.Code,
	})
	if err != nil {
		return IngestResponse{NodeID: req.NodeID}, err
	}
	return IngestResponse{NodeID: r.NodeID, Summary: r.Summary, Tags: r.Tags}, nil
}

func (b *impl) Enrich(ctx context.Context, req EnrichRequest) (EnrichResponse, error) {
	// Always load summaries from SQLite — fast path, no LLM.
	summaries := b.store.GetSummaries(req.AllNodeIDs)

	if !b.cfg.Enrich {
		return EnrichResponse{Summaries: summaries}, nil
	}

	r, err := b.enricher.Enrich(ctx, enricher.Request{
		RootID:       req.RootID,
		RootName:     req.RootName,
		RootType:     req.RootType,
		CalleeNames:  req.CalleeNames,
		CallerNames:  req.CallerNames,
		RelatedNames: req.RelatedNames,
		TaskContext:  req.TaskContext,
	})
	if err != nil {
		// Return summaries even if insight generation failed.
		return EnrichResponse{Summaries: summaries}, nil
	}
	return EnrichResponse{
		Insight:   r.Insight,
		Concerns:  r.Concerns,
		Summaries: summaries,
		LLMUsed:   r.LLMUsed,
	}, nil
}

func (b *impl) ExplainViolation(ctx context.Context, req ViolationRequest) (ViolationResponse, error) {
	if !b.cfg.Guardian {
		return ViolationResponse{}, nil
	}
	r, err := b.guardian.Explain(ctx, guardian.Request{
		RuleID:       req.RuleID,
		RuleSeverity: req.RuleSeverity,
		Description:  req.Description,
		SourceFile:   req.SourceFile,
		TargetName:   req.TargetName,
	})
	if err != nil {
		return ViolationResponse{}, err
	}
	return ViolationResponse{Explanation: r.Explanation, Fix: r.Fix}, nil
}

func (b *impl) Coordinate(ctx context.Context, req CoordinateRequest) (CoordinateResponse, error) {
	if !b.cfg.Orchestrate {
		return CoordinateResponse{}, nil
	}

	claims := make([]orchestrator.WorkClaim, len(req.ConflictingClaims))
	for i, c := range req.ConflictingClaims {
		claims[i] = orchestrator.WorkClaim{
			AgentID:   c.AgentID,
			Scope:     c.Scope,
			ScopeType: c.ScopeType,
		}
	}
	r, err := b.orchestrator.Coordinate(ctx, orchestrator.Request{
		NewAgentID:        req.NewAgentID,
		NewScope:          req.NewScope,
		ConflictingClaims: claims,
	})
	if err != nil {
		return CoordinateResponse{}, err
	}
	return CoordinateResponse{
		Suggestion:       r.Suggestion,
		AlternativeScope: r.AlternativeScope,
	}, nil
}

func (b *impl) Summary(nodeID string) string {
	if b.store == nil {
		return ""
	}
	return b.store.GetSummary(nodeID)
}

func (b *impl) Available() bool {
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	return b.llm.Available(ctx)
}

func (b *impl) ModelName() string {
	return b.llm.ModelName()
}

func (b *impl) EnsureModel(ctx context.Context, w io.Writer) error {
	if b.llm.ModelPulled(ctx) {
		return nil
	}
	return b.llm.PullModel(ctx, w)
}

func (b *impl) BuildContextPacket(ctx context.Context, req ContextPacketRequest) (*ContextPacket, error) {
	if !b.cfg.ContextBuilder {
		return nil, nil // feature disabled; caller uses raw context
	}
	pkt, err := b.builder.Build(ctx, contextbuilder.Request{
		AgentID:         req.AgentID,
		Phase:           string(req.Phase),
		QualityMode:     string(req.QualityMode),
		EnableLLM:       req.EnableLLM,
		RootNodeID:      req.Snapshot.RootNodeID,
		RootName:        req.Snapshot.RootName,
		RootType:        req.Snapshot.RootType,
		RootFile:        req.Snapshot.RootFile,
		CalleeNames:     req.Snapshot.CalleeNames,
		CallerNames:     req.Snapshot.CallerNames,
		RelatedNames:    req.Snapshot.RelatedNames,
		ApplicableRules: toBuilderRules(req.Snapshot.ApplicableRules),
		ActiveClaims:    toBuilderClaims(req.Snapshot.ActiveClaims),
		TaskContext:     req.Snapshot.TaskContext,
		TaskID:          req.Snapshot.TaskID,
	})
	if err != nil || pkt == nil {
		return nil, err
	}
	return toContextPacket(pkt), nil
}

func (b *impl) LogDecision(_ context.Context, req DecisionRequest) error {
	return b.learner.RecordDecision(contextbuilder.DecisionInput{
		AgentID:         req.AgentID,
		Phase:           req.Phase,
		EntityName:      req.EntityName,
		Action:          req.Action,
		RelatedEntities: req.RelatedEntities,
		Outcome:         req.Outcome,
		Notes:           req.Notes,
	})
}

func (b *impl) SetSDLCPhase(phase SDLCPhase, agentID string) error {
	return b.sdlcMgr.SetPhase(string(phase), agentID)
}

func (b *impl) SetQualityMode(mode QualityMode, agentID string) error {
	return b.sdlcMgr.SetQualityMode(string(mode), agentID)
}

func (b *impl) GetSDLCConfig() SDLCConfig {
	row := b.sdlcMgr.GetConfig()
	return SDLCConfig{
		Phase:       SDLCPhase(row.Phase),
		QualityMode: QualityMode(row.QualityMode),
		UpdatedAt:   row.UpdatedAt,
		UpdatedBy:   row.UpdatedBy,
	}
}

func (b *impl) GetPatterns(trigger string, limit int) []PatternHint {
	if limit <= 0 {
		limit = 20
	}
	var raw []store.ContextPattern
	if trigger != "" {
		raw = b.store.GetPatternsForTriggers([]string{trigger}, limit)
	} else {
		all, _ := b.store.AllPatterns()
		if len(all) > limit {
			all = all[:limit]
		}
		raw = all
	}
	out := make([]PatternHint, len(raw))
	for i, p := range raw {
		out[i] = PatternHint{Trigger: p.Trigger, CoChange: p.CoChange, Reason: p.Reason, Confidence: p.Confidence}
	}
	return out
}

// --- conversion helpers ---

func toBuilderRules(rules []RuleInput) []contextbuilder.RuleRef {
	out := make([]contextbuilder.RuleRef, len(rules))
	for i, r := range rules {
		out[i] = contextbuilder.RuleRef{RuleID: r.RuleID, Severity: r.Severity, Description: r.Description}
	}
	return out
}

func toBuilderClaims(claims []ClaimInput) []contextbuilder.ClaimRef {
	out := make([]contextbuilder.ClaimRef, len(claims))
	for i, c := range claims {
		out[i] = contextbuilder.ClaimRef{AgentID: c.AgentID, Scope: c.Scope, ScopeType: c.ScopeType, ExpiresAt: c.ExpiresAt}
	}
	return out
}

func toContextPacket(p *contextbuilder.Packet) *ContextPacket {
	pkt := &ContextPacket{
		AgentID:             p.AgentID,
		EntityName:          p.EntityName,
		EntityType:          p.EntityType,
		GeneratedAt:         p.GeneratedAt,
		Phase:               SDLCPhase(p.Phase),
		QualityMode:         QualityMode(p.QualityMode),
		RootSummary:         p.RootSummary,
		DependencySummaries: p.DependencySummaries,
		Insight:             p.Insight,
		Concerns:            p.Concerns,
		PhaseGuidance:       p.PhaseGuidance,
		LLMUsed:             p.LLMUsed,
		PacketQuality:       p.PacketQuality,
		QualityGate: QualityGate{
			RequireTests:   p.Gate.RequireTests,
			RequireDocs:    p.Gate.RequireDocs,
			RequirePRCheck: p.Gate.RequirePRCheck,
			Checklist:      p.Gate.Checklist,
		},
	}
	for _, c := range p.ActiveConstraints {
		pkt.ActiveConstraints = append(pkt.ActiveConstraints, ConstraintItem{
			RuleID: c.RuleID, Severity: c.Severity, Description: c.Description, Hint: c.Hint,
		})
	}
	for _, a := range p.TeamStatus {
		pkt.TeamStatus = append(pkt.TeamStatus, AgentStatus{
			AgentID: a.AgentID, Scope: a.Scope, ScopeType: a.ScopeType, ExpiresIn: a.ExpiresIn,
		})
	}
	for _, ph := range p.PatternHints {
		pkt.PatternHints = append(pkt.PatternHints, PatternHint{
			Trigger: ph.Trigger, CoChange: ph.CoChange, Reason: ph.Reason, Confidence: ph.Confidence,
		})
	}
	return pkt
}
